# Generated by Django 4.2 on 2023-04-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vtx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='dispositivo')),
                ('address', models.IntegerField(default=1, unique=True, verbose_name='endereço')),
                ('port', models.CharField(default='COM4', max_length=20, verbose_name='porta')),
                ('boudrate', models.IntegerField(default=19200, verbose_name='BoudRate')),
                ('online', models.BooleanField(verbose_name='Online')),
            ],
            options={
                'verbose_name': 'Gateway',
                'verbose_name_plural': 'Gateways',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Equipamento')),
                ('vibraX', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='X Veloc RMS')),
                ('vibraZ', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Z Veloc RMS')),
                ('vibraX2', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='X Acele Pico')),
                ('vibraZ2', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Z Acele Pico')),
                ('corrente', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Corrente')),
                ('temp', models.DecimalField(decimal_places=1, default=0.0, max_digits=12, verbose_name='Temperatura')),
                ('estado', models.CharField(max_length=30, verbose_name='Estado')),
                ('online', models.BooleanField(verbose_name='Online')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
            },
        ),
        migrations.CreateModel(
            name='NodeSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeId', models.IntegerField(default=1, verbose_name='Node')),
                ('address', models.IntegerField(default=1, verbose_name='endereço')),
                ('ciclo', models.IntegerField(default=60, verbose_name='ciclo de logs (s)')),
                ('addrVibraX', models.IntegerField(default=1, verbose_name='endereço X Veloc RMS')),
                ('addrVibraZ', models.IntegerField(default=1, verbose_name='endereço Z Veloc RMS')),
                ('addrVibraX2', models.IntegerField(default=1, verbose_name='endereço X Acele Pico')),
                ('addrVibraZ2', models.IntegerField(default=1, verbose_name='endereço Z Acele Pico')),
                ('addrTemp', models.IntegerField(default=1, verbose_name='endereço Temperatura')),
                ('addrCorrente', models.IntegerField(default=1, verbose_name='endereço Corrente')),
                ('alertVibraX', models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert X Veloc - nv1')),
                ('alertVibraZ', models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert Z Veloc - nv1')),
                ('alertTemp', models.DecimalField(decimal_places=1, default=50.0, max_digits=12, verbose_name='Alert Temperatura nv1')),
                ('alertCorrente', models.DecimalField(decimal_places=2, default=10.0, max_digits=12, verbose_name='Alert Corrente nv1')),
                ('alertVibraXNv2', models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert X Veloc - nv2')),
                ('alertVibraZNv2', models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert Z Veloc - nv2')),
                ('alertTempNv2', models.DecimalField(decimal_places=1, default=70.0, max_digits=12, verbose_name='Alert Temperatura nv2')),
                ('alertVibraX2', models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert X Acele - nv1')),
                ('alertVibraZ2', models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert Z Acele - nv1')),
                ('alertVibraX2Nv2', models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert X Acele - nv2')),
                ('alertVibraZ2Nv2', models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert Z Acele - nv2')),
                ('alertCorrenteNv2', models.DecimalField(decimal_places=2, default=20.0, max_digits=12, verbose_name='Alert Corrente nv2')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtx.node')),
            ],
            options={
                'verbose_name': 'NodeSetup',
                'verbose_name_plural': 'NodeSetups',
            },
        ),
        migrations.CreateModel(
            name='Hist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('alertVibraX', models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert X Veloc - nv1')),
                ('alertVibraZ', models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert Z Veloc - nv1')),
                ('alertTemp', models.DecimalField(decimal_places=1, default=50.0, max_digits=12, verbose_name='Alert Temperatura nv1')),
                ('alertCorrente', models.DecimalField(decimal_places=2, default=10.0, max_digits=12, verbose_name='Alert Corrente nv1')),
                ('alertVibraXNv2', models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert X Veloc - nv2')),
                ('alertVibraZNv2', models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert Z Veloc - nv2')),
                ('alertTempNv2', models.DecimalField(decimal_places=1, default=70.0, max_digits=12, verbose_name='Alert Temperatura nv2')),
                ('alertVibraX2', models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert X Acele - nv1')),
                ('alertVibraZ2', models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert Z Acele - nv1')),
                ('alertVibraX2Nv2', models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert X Acele - nv2')),
                ('alertVibraZ2Nv2', models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert Z Acele - nv2')),
                ('alertCorrenteNv2', models.DecimalField(decimal_places=2, default=20.0, max_digits=12, verbose_name='Alert Corrente nv2')),
                ('vibraX', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='X Veloc RMS')),
                ('vibraZ', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Z Veloc RMS')),
                ('vibraX2', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='X Acele Pico')),
                ('vibraZ2', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Z Acele Pico')),
                ('temp', models.DecimalField(decimal_places=1, default=0.0, max_digits=12, verbose_name='Temperatura')),
                ('corrente', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Corrente')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtx.node')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('descricao', models.CharField(default='generico', max_length=50, verbose_name='Evento')),
                ('tipo', models.CharField(default='Evento', max_length=50, verbose_name='tipo de Evento')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtx.node')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
