# Generated by Django 4.2 on 2023-04-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtx', '0002_gateway_node_nodesetup_hist_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='alerta',
            field=models.CharField(default='000000', max_length=30, verbose_name='alerta'),
        ),
    ]
