# Generated by Django 3.2.18 on 2023-04-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtx', '0004_alter_node_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='estado',
            field=models.CharField(choices=[('1', 'Ok'), ('2', 'Falha'), ('3', 'Alerta'), ('0', 'Desconhecido')], default='0', max_length=2, verbose_name='Estado'),
        ),
    ]
