# Generated by Django 3.2.18 on 2023-04-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtx', '0005_alter_node_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesetup',
            name='fatorCorrente',
            field=models.IntegerField(default=1, verbose_name='fator Corrente'),
        ),
        migrations.AddField(
            model_name='nodesetup',
            name='fatorTemp',
            field=models.IntegerField(default=100, verbose_name='fator Temperatura'),
        ),
        migrations.AddField(
            model_name='nodesetup',
            name='fatorVibraX',
            field=models.IntegerField(default=1000, verbose_name='fator X Veloc RMS'),
        ),
        migrations.AddField(
            model_name='nodesetup',
            name='fatorVibraX2',
            field=models.IntegerField(default=1000, verbose_name='fator X Acele Pico'),
        ),
        migrations.AddField(
            model_name='nodesetup',
            name='fatorVibraZ',
            field=models.IntegerField(default=1000, verbose_name='fator Z Veloc RMS'),
        ),
        migrations.AddField(
            model_name='nodesetup',
            name='fatorVibraZ2',
            field=models.IntegerField(default=1000, verbose_name='fator Z Acele Pico'),
        ),
    ]
