# Generated by Django 3.2.18 on 2023-04-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtx', '0006_auto_20230429_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hist',
            name='date',
            field=models.DateTimeField(verbose_name='Data'),
        ),
    ]
