# Generated by Django 3.2.18 on 2023-04-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtx', '0007_alter_hist_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hist',
            old_name='date',
            new_name='time',
        ),
    ]
