# Generated by Django 3.2.18 on 2023-05-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtx', '0008_rename_date_hist_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='configurar',
            field=models.BooleanField(default=False, verbose_name='Configrando'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='configurarMsg',
            field=models.CharField(default='ok', max_length=20, verbose_name='config msg'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='configurarStatus',
            field=models.IntegerField(default=0, verbose_name='status Configurar'),
        ),
    ]
