# Generated by Django 3.2.18 on 2023-05-01 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vtx', '0009_auto_20230501_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('limiarPico', models.DecimalField(decimal_places=3, default=5, max_digits=12, verbose_name='limiar para pico %')),
                ('limiarMedia', models.DecimalField(decimal_places=3, default=2, max_digits=12, verbose_name='limiar para media %')),
                ('picoVibraX', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Pico X RMS')),
                ('mediaVibraX', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Media X RMS')),
                ('picoVibraX2', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Pico X Pico')),
                ('mediaVibraX2', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Media X Pico')),
                ('picoVibraZ', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Pico Z RMS')),
                ('mediaVibraZ', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Media Z RMS')),
                ('picoVibraZ2', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Pico Z Pico')),
                ('mediaVibraZ2', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Media Z Pico')),
                ('picoTemp', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Pico T')),
                ('mediaTemp', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Media T')),
                ('picoCorrente', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Pico Corrente')),
                ('mediaCorrente', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Media Corrente')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtx.node')),
            ],
        ),
        migrations.AddField(
            model_name='nodesetup',
            name='aprenderCiclo',
            field=models.IntegerField(default=60, verbose_name='tempo entre medicoes p/ Apdr'),
        ),
        migrations.AddField(
            model_name='nodesetup',
            name='aprenderTime',
            field=models.IntegerField(default=10, verbose_name='qtds de medicoes para Aprender'),
        ),
        migrations.CreateModel(
            name='AprendizadoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Data')),
                ('vibraX', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='X Veloc RMS')),
                ('vibraZ', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Z Veloc RMS')),
                ('vibraX2', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='X Acele Pico')),
                ('vibraZ2', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Z Acele Pico')),
                ('temp', models.DecimalField(decimal_places=1, default=0.0, max_digits=12, verbose_name='Temperatura')),
                ('corrente', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Corrente')),
                ('aprendizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtx.aprendizado')),
            ],
        ),
    ]
