# Generated by Django 3.2.18 on 2023-05-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtx', '0010_auto_20230501_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='aprender',
            field=models.BooleanField(default=False, verbose_name='Aprender'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='motorIndex',
            field=models.IntegerField(default=0, verbose_name='Motor alvo'),
        ),
    ]
